---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

patchesStrategicMerge:
  - patches/localrules-labels.yml

resources:
  - dashboards
  - localrules.yaml
  - rbac.yaml
