---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  ROOK_CSI_CEPH_IMAGE: "registry.sighup.io/fury/cephcsi/cephcsi:v3.7.2"
  ROOK_CSI_REGISTRAR_IMAGE: "registry.sighup.io/fury/sig-storage/csi-node-driver-registrar:v2.5.1"
  ROOK_CSI_RESIZER_IMAGE: "registry.sighup.io/fury/sig-storage/csi-resizer:v1.6.0"
  ROOK_CSI_PROVISIONER_IMAGE: "registry.sighup.io/fury/sig-storage/csi-provisioner:v3.3.0"
  ROOK_CSI_SNAPSHOTTER_IMAGE: "registry.sighup.io/fury/sig-storage/csi-snapshotter:v6.1.0"
  ROOK_CSI_ATTACHER_IMAGE: "registry.sighup.io/fury/sig-storage/csi-attacher:v4.0.0"
